### ISSUE TITLE
Unable to run

### ISSUE THREAD

**Issue by huzoorbux** [gustavoSoriano/whatsapp-bot-python3#1]
Aguardando 30 segundos para sincronização do QRCode
Enviando mensagem para Maria
Traceback (most recent call last):
  File "E:\py\whatsapp-bot-python3-master\app.py", line 41, in <module>
    bot.envia_contatos(" Mensagem automatizada via Bot ")
  File "E:\py\whatsapp-bot-python3-master\app.py", line 27, in envia_contatos
    pessoa = self.driver.find_element_by_xpath(f"//span[@title='{pessoa}']")
  File "C:\Users\huzoo\AppData\Local\Programs\Python\Python38-32\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 394, in find_element_by_xpath
    return self.find_element(by=By.XPATH, value=xpath)
  File "C:\Users\huzoo\AppData\Local\Programs\Python\Python38-32\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 976, in find_element
    return self.execute(Command.FIND_ELEMENT, {
  File "C:\Users\huzoo\AppData\Local\Programs\Python\Python38-32\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Users\huzoo\AppData\Local\Programs\Python\Python38-32\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"xpath","selector":"//span[@title='Maria']"}
  (Session info: chrome=78.0.3904.97)

**Comment by Web-Devv** [comment]
@huzoorbux The selection is made through contact name
`selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"xpath","selector":"//span[@title='Maria']"}`

This happens because you don't have someone named 'Maria' in your contact list. I'll catch this and log as an exception. :)

**Comment by marcioboaro** [comment]
Soriano por favor gostaria de ajuda, estava funcionando, agora não funciona mais, não acha os contatos (selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element:) contatos que eu tenho. O que poderia ser?

**Comment by Web-Devv** [comment]
Opa, blz ?  então, removi o método de envio pelo nome de contato, mas você ainda pode enviar através do número de telefone. 
Um ponto importante também, é sempre baixar a versão correta do Chromedriver. Os detalhes estão no Readme.
Obrigado
